import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Download, Share2, Printer, ArrowUpRight } from 'lucide-react';
import { MOCK_ACTIONS } from '../constants';

const ReportPage: React.FC = () => {
  const emissionsData = [
    { name: '2022', Scope1: 20, Scope2: 35 },
    { name: '2023', Scope1: 25, Scope2: 32 },
    { name: '2024 (YTD)', Scope1: 18, Scope2: 28 },
  ];

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Sustainability Report 2024</h1>
          <p className="text-slate-500">Draft • VSME Basic Aligned</p>
        </div>
        <div className="flex gap-2">
            <button className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors">
                <Printer size={16} /> Print
            </button>
            <button className="flex items-center gap-2 px-3 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors shadow-sm">
                <Download size={16} /> Export PDF
            </button>
        </div>
      </div>

      {/* Report Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Narrative & Charts */}
          <div className="lg:col-span-2 space-y-8">
              {/* Executive Summary Section */}
              <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                  <h2 className="text-lg font-semibold text-slate-800 mb-4 border-b border-slate-100 pb-2">Executive Summary</h2>
                  <div className="prose prose-slate prose-sm max-w-none text-slate-600">
                      <p className="mb-3">
                          In 2024, <strong>Viet Manufacturing Co., Ltd</strong> has made significant strides in establishing a baseline for its environmental impact. 
                          We have successfully tracked 100% of our Scope 2 (Electricity) emissions and 85% of our Scope 1 (Fuel) sources.
                      </p>
                      <p className="mb-3">
                          Our total carbon footprint is estimated at <strong>245 tCO2e</strong> for the reporting period. 
                          Compared to the previous year, we observe a <span className="text-green-600 font-medium">5% reduction in energy intensity</span> per unit of production.
                      </p>
                      <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500 text-indigo-900 italic my-4">
                          "This draft summary was generated by GreenPath Copilot based on your inputs in the Assessment module."
                      </div>
                  </div>
              </div>

              {/* Emissions Chart */}
              <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                   <h2 className="text-lg font-semibold text-slate-800 mb-6">GHG Emissions Trend (tCO2e)</h2>
                   <div className="h-72 w-full">
                       <ResponsiveContainer width="100%" height="100%">
                           <BarChart data={emissionsData}>
                               <CartesianGrid strokeDasharray="3 3" vertical={false} />
                               <XAxis dataKey="name" tick={{fontSize: 12, fill: '#64748b'}} axisLine={false} tickLine={false} />
                               <YAxis tick={{fontSize: 12, fill: '#64748b'}} axisLine={false} tickLine={false} />
                               <Tooltip 
                                  cursor={{fill: '#f1f5f9'}}
                                  contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}
                               />
                               <Legend />
                               <Bar dataKey="Scope1" name="Scope 1 (Direct)" fill="#F59E0B" radius={[4, 4, 0, 0]} />
                               <Bar dataKey="Scope2" name="Scope 2 (Energy)" fill="#10B981" radius={[4, 4, 0, 0]} />
                           </BarChart>
                       </ResponsiveContainer>
                   </div>
              </div>
          </div>

          {/* Action Plan Sidebar */}
          <div className="space-y-6">
              <div className="bg-slate-900 text-white p-6 rounded-xl shadow-lg">
                  <h3 className="font-semibold text-lg mb-1">Action Plan</h3>
                  <p className="text-slate-400 text-sm mb-6">Strategic initiatives to improve ESG performance.</p>
                  
                  <div className="space-y-4">
                      {MOCK_ACTIONS.map((action) => (
                          <div key={action.id} className="bg-slate-800 p-4 rounded-lg border border-slate-700">
                              <div className="flex justify-between items-start mb-2">
                                  <h4 className="font-medium text-sm text-white">{action.title}</h4>
                                  <span className={`text-[10px] uppercase px-2 py-0.5 rounded font-bold ${
                                      action.status === 'In Progress' ? 'bg-blue-900 text-blue-200' : 'bg-slate-700 text-slate-300'
                                  }`}>
                                      {action.status}
                                  </span>
                              </div>
                              <div className="flex gap-2 mt-3">
                                  <span className="text-[10px] px-2 py-1 bg-slate-700 rounded text-slate-300">
                                      Impact: <span className="text-white">{action.impact}</span>
                                  </span>
                                  <span className="text-[10px] px-2 py-1 bg-slate-700 rounded text-slate-300">
                                      Effort: <span className="text-white">{action.effort}</span>
                                  </span>
                              </div>
                          </div>
                      ))}
                  </div>
                  
                  <button className="w-full mt-6 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2">
                      Generate New Actions <ArrowUpRight size={16} />
                  </button>
              </div>
          </div>
      </div>
    </div>
  );
};

export default ReportPage;